// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: follower/follower.proto

package follower

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_follower_follower_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follower_follower_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_follower_follower_proto_rawDescGZIP(), []int{0}
}

func (x *FollowRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type FollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowResponse) Reset() {
	*x = FollowResponse{}
	mi := &file_follower_follower_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResponse) ProtoMessage() {}

func (x *FollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follower_follower_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResponse.ProtoReflect.Descriptor instead.
func (*FollowResponse) Descriptor() ([]byte, []int) {
	return file_follower_follower_proto_rawDescGZIP(), []int{1}
}

func (x *FollowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UnfollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowRequest) Reset() {
	*x = UnfollowRequest{}
	mi := &file_follower_follower_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowRequest) ProtoMessage() {}

func (x *UnfollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follower_follower_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowRequest.ProtoReflect.Descriptor instead.
func (*UnfollowRequest) Descriptor() ([]byte, []int) {
	return file_follower_follower_proto_rawDescGZIP(), []int{2}
}

func (x *UnfollowRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type UnfollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowResponse) Reset() {
	*x = UnfollowResponse{}
	mi := &file_follower_follower_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowResponse) ProtoMessage() {}

func (x *UnfollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follower_follower_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowResponse.ProtoReflect.Descriptor instead.
func (*UnfollowResponse) Descriptor() ([]byte, []int) {
	return file_follower_follower_proto_rawDescGZIP(), []int{3}
}

func (x *UnfollowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingRequest) Reset() {
	*x = GetFollowingRequest{}
	mi := &file_follower_follower_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingRequest) ProtoMessage() {}

func (x *GetFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follower_follower_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingRequest) Descriptor() ([]byte, []int) {
	return file_follower_follower_proto_rawDescGZIP(), []int{4}
}

func (x *GetFollowingRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Following     []string               `protobuf:"bytes,1,rep,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingResponse) Reset() {
	*x = GetFollowingResponse{}
	mi := &file_follower_follower_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingResponse) ProtoMessage() {}

func (x *GetFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follower_follower_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingResponse.ProtoReflect.Descriptor instead.
func (*GetFollowingResponse) Descriptor() ([]byte, []int) {
	return file_follower_follower_proto_rawDescGZIP(), []int{5}
}

func (x *GetFollowingResponse) GetFollowing() []string {
	if x != nil {
		return x.Following
	}
	return nil
}

type GetFollowersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersRequest) Reset() {
	*x = GetFollowersRequest{}
	mi := &file_follower_follower_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersRequest) ProtoMessage() {}

func (x *GetFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follower_follower_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersRequest.ProtoReflect.Descriptor instead.
func (*GetFollowersRequest) Descriptor() ([]byte, []int) {
	return file_follower_follower_proto_rawDescGZIP(), []int{6}
}

func (x *GetFollowersRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetFollowersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Followers     []string               `protobuf:"bytes,1,rep,name=followers,proto3" json:"followers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersResponse) Reset() {
	*x = GetFollowersResponse{}
	mi := &file_follower_follower_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersResponse) ProtoMessage() {}

func (x *GetFollowersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follower_follower_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersResponse.ProtoReflect.Descriptor instead.
func (*GetFollowersResponse) Descriptor() ([]byte, []int) {
	return file_follower_follower_proto_rawDescGZIP(), []int{7}
}

func (x *GetFollowersResponse) GetFollowers() []string {
	if x != nil {
		return x.Followers
	}
	return nil
}

type RecommendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendRequest) Reset() {
	*x = RecommendRequest{}
	mi := &file_follower_follower_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendRequest) ProtoMessage() {}

func (x *RecommendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follower_follower_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendRequest.ProtoReflect.Descriptor instead.
func (*RecommendRequest) Descriptor() ([]byte, []int) {
	return file_follower_follower_proto_rawDescGZIP(), []int{8}
}

type RecommendResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RecommendedUsers []*RecDTO              `protobuf:"bytes,1,rep,name=recommended_users,json=recommendedUsers,proto3" json:"recommended_users,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecommendResponse) Reset() {
	*x = RecommendResponse{}
	mi := &file_follower_follower_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResponse) ProtoMessage() {}

func (x *RecommendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follower_follower_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResponse.ProtoReflect.Descriptor instead.
func (*RecommendResponse) Descriptor() ([]byte, []int) {
	return file_follower_follower_proto_rawDescGZIP(), []int{9}
}

func (x *RecommendResponse) GetRecommendedUsers() []*RecDTO {
	if x != nil {
		return x.RecommendedUsers
	}
	return nil
}

type RecDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Mutuals       int64                  `protobuf:"varint,2,opt,name=mutuals,proto3" json:"mutuals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecDTO) Reset() {
	*x = RecDTO{}
	mi := &file_follower_follower_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecDTO) ProtoMessage() {}

func (x *RecDTO) ProtoReflect() protoreflect.Message {
	mi := &file_follower_follower_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecDTO.ProtoReflect.Descriptor instead.
func (*RecDTO) Descriptor() ([]byte, []int) {
	return file_follower_follower_proto_rawDescGZIP(), []int{10}
}

func (x *RecDTO) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RecDTO) GetMutuals() int64 {
	if x != nil {
		return x.Mutuals
	}
	return 0
}

var File_follower_follower_proto protoreflect.FileDescriptor

const file_follower_follower_proto_rawDesc = "" +
	"\n" +
	"\x17follower/follower.proto\x12\bfollower\x1a\x1cgoogle/api/annotations.proto\x1a\x15google/api/http.proto\"\x1f\n" +
	"\rFollowRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\"(\n" +
	"\x0eFollowResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"!\n" +
	"\x0fUnfollowRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\"*\n" +
	"\x10UnfollowResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"1\n" +
	"\x13GetFollowingRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"4\n" +
	"\x14GetFollowingResponse\x12\x1c\n" +
	"\tfollowing\x18\x01 \x03(\tR\tfollowing\"1\n" +
	"\x13GetFollowersRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"4\n" +
	"\x14GetFollowersResponse\x12\x1c\n" +
	"\tfollowers\x18\x01 \x03(\tR\tfollowers\"\x12\n" +
	"\x10RecommendRequest\"R\n" +
	"\x11RecommendResponse\x12=\n" +
	"\x11recommended_users\x18\x01 \x03(\v2\x10.follower.RecDTOR\x10recommendedUsers\">\n" +
	"\x06RecDTO\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x18\n" +
	"\amutuals\x18\x02 \x01(\x03R\amutuals2\x85\x04\n" +
	"\x0fFollowerService\x12S\n" +
	"\x06Follow\x12\x17.follower.FollowRequest\x1a\x18.follower.FollowResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/api/follow\x12[\n" +
	"\bUnfollow\x12\x19.follower.UnfollowRequest\x1a\x1a.follower.UnfollowResponse\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/api/follow/{to}\x12p\n" +
	"\fGetFollowing\x12\x1d.follower.GetFollowingRequest\x1a\x1e.follower.GetFollowingResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/following/{username}\x12p\n" +
	"\fGetFollowers\x12\x1d.follower.GetFollowersRequest\x1a\x1e.follower.GetFollowersResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/followers/{username}\x12\\\n" +
	"\tRecommend\x12\x1a.follower.RecommendRequest\x1a\x1b.follower.RecommendResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/recommendB\x1bZ\x19soa-team-5/proto/followerb\x06proto3"

var (
	file_follower_follower_proto_rawDescOnce sync.Once
	file_follower_follower_proto_rawDescData []byte
)

func file_follower_follower_proto_rawDescGZIP() []byte {
	file_follower_follower_proto_rawDescOnce.Do(func() {
		file_follower_follower_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_follower_follower_proto_rawDesc), len(file_follower_follower_proto_rawDesc)))
	})
	return file_follower_follower_proto_rawDescData
}

var file_follower_follower_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_follower_follower_proto_goTypes = []any{
	(*FollowRequest)(nil),        // 0: follower.FollowRequest
	(*FollowResponse)(nil),       // 1: follower.FollowResponse
	(*UnfollowRequest)(nil),      // 2: follower.UnfollowRequest
	(*UnfollowResponse)(nil),     // 3: follower.UnfollowResponse
	(*GetFollowingRequest)(nil),  // 4: follower.GetFollowingRequest
	(*GetFollowingResponse)(nil), // 5: follower.GetFollowingResponse
	(*GetFollowersRequest)(nil),  // 6: follower.GetFollowersRequest
	(*GetFollowersResponse)(nil), // 7: follower.GetFollowersResponse
	(*RecommendRequest)(nil),     // 8: follower.RecommendRequest
	(*RecommendResponse)(nil),    // 9: follower.RecommendResponse
	(*RecDTO)(nil),               // 10: follower.RecDTO
}
var file_follower_follower_proto_depIdxs = []int32{
	10, // 0: follower.RecommendResponse.recommended_users:type_name -> follower.RecDTO
	0,  // 1: follower.FollowerService.Follow:input_type -> follower.FollowRequest
	2,  // 2: follower.FollowerService.Unfollow:input_type -> follower.UnfollowRequest
	4,  // 3: follower.FollowerService.GetFollowing:input_type -> follower.GetFollowingRequest
	6,  // 4: follower.FollowerService.GetFollowers:input_type -> follower.GetFollowersRequest
	8,  // 5: follower.FollowerService.Recommend:input_type -> follower.RecommendRequest
	1,  // 6: follower.FollowerService.Follow:output_type -> follower.FollowResponse
	3,  // 7: follower.FollowerService.Unfollow:output_type -> follower.UnfollowResponse
	5,  // 8: follower.FollowerService.GetFollowing:output_type -> follower.GetFollowingResponse
	7,  // 9: follower.FollowerService.GetFollowers:output_type -> follower.GetFollowersResponse
	9,  // 10: follower.FollowerService.Recommend:output_type -> follower.RecommendResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_follower_follower_proto_init() }
func file_follower_follower_proto_init() {
	if File_follower_follower_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_follower_follower_proto_rawDesc), len(file_follower_follower_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_follower_follower_proto_goTypes,
		DependencyIndexes: file_follower_follower_proto_depIdxs,
		MessageInfos:      file_follower_follower_proto_msgTypes,
	}.Build()
	File_follower_follower_proto = out.File
	file_follower_follower_proto_goTypes = nil
	file_follower_follower_proto_depIdxs = nil
}
