"""add tour_name to purchase_tokens

Revision ID: 515d1b7626cf
Revises: 
Create Date: 2025-09-18 01:12:53.745518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515d1b7626cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_tokens', sa.Column('tour_name', sa.String(), nullable=True))
    op.add_column('purchase_tokens', sa.Column('price', sa.Float(), nullable=True))

    op.add_column('purchase_tokens', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE purchase_tokens SET created_at = NOW()")
    op.alter_column('purchase_tokens', 'created_at', nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_tokens', 'price')
    op.drop_column('purchase_tokens', 'tour_name')
    # ### end Alembic commands ###
