// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: stakeholders/stakeholders.proto

package stakeholders

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type GetAllUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersRequest) Reset() {
	*x = GetAllUsersRequest{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersRequest) ProtoMessage() {}

func (x *GetAllUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersRequest.ProtoReflect.Descriptor instead.
func (*GetAllUsersRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{4}
}

type GetAllUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersResponse) Reset() {
	*x = GetAllUsersResponse{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersResponse) ProtoMessage() {}

func (x *GetAllUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersResponse.ProtoReflect.Descriptor instead.
func (*GetAllUsersResponse) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type BlockUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	IsBlocked     bool                   `protobuf:"varint,2,opt,name=isBlocked,proto3" json:"isBlocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUserRequest) Reset() {
	*x = BlockUserRequest{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserRequest) ProtoMessage() {}

func (x *BlockUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserRequest.ProtoReflect.Descriptor instead.
func (*BlockUserRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{6}
}

func (x *BlockUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BlockUserRequest) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

type BlockUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUserResponse) Reset() {
	*x = BlockUserResponse{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserResponse) ProtoMessage() {}

func (x *BlockUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserResponse.ProtoReflect.Descriptor instead.
func (*BlockUserResponse) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{7}
}

func (x *BlockUserResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetProfileByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByUsernameRequest) Reset() {
	*x = GetProfileByUsernameRequest{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByUsernameRequest) ProtoMessage() {}

func (x *GetProfileByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByUsernameRequest.ProtoReflect.Descriptor instead.
func (*GetProfileByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{8}
}

func (x *GetProfileByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{9}
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateProfileRequest) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateProfileResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UserProfileResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Username       string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FirstName      string                 `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName       string                 `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	ProfilePicture string                 `protobuf:"bytes,4,opt,name=profilePicture,proto3" json:"profilePicture,omitempty"`
	Biography      string                 `protobuf:"bytes,5,opt,name=biography,proto3" json:"biography,omitempty"`
	Motto          string                 `protobuf:"bytes,6,opt,name=motto,proto3" json:"motto,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserProfileResponse) Reset() {
	*x = UserProfileResponse{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileResponse) ProtoMessage() {}

func (x *UserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileResponse.ProtoReflect.Descriptor instead.
func (*UserProfileResponse) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{12}
}

func (x *UserProfileResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfileResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserProfileResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserProfileResponse) GetProfilePicture() string {
	if x != nil {
		return x.ProfilePicture
	}
	return ""
}

func (x *UserProfileResponse) GetBiography() string {
	if x != nil {
		return x.Biography
	}
	return ""
}

func (x *UserProfileResponse) GetMotto() string {
	if x != nil {
		return x.Motto
	}
	return ""
}

type UserProfile struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FirstName      string                 `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName       string                 `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	ProfilePicture string                 `protobuf:"bytes,3,opt,name=profilePicture,proto3" json:"profilePicture,omitempty"`
	Biography      string                 `protobuf:"bytes,4,opt,name=biography,proto3" json:"biography,omitempty"`
	Motto          string                 `protobuf:"bytes,5,opt,name=motto,proto3" json:"motto,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{13}
}

func (x *UserProfile) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserProfile) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserProfile) GetProfilePicture() string {
	if x != nil {
		return x.ProfilePicture
	}
	return ""
}

func (x *UserProfile) GetBiography() string {
	if x != nil {
		return x.Biography
	}
	return ""
}

func (x *UserProfile) GetMotto() string {
	if x != nil {
		return x.Motto
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	IsBlocked     bool                   `protobuf:"varint,5,opt,name=isBlocked,proto3" json:"isBlocked,omitempty"`
	Profile       *UserProfile           `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{14}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

func (x *User) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

var File_stakeholders_stakeholders_proto protoreflect.FileDescriptor

const file_stakeholders_stakeholders_proto_rawDesc = "" +
	"\n" +
	"\x1fstakeholders/stakeholders.proto\x12\fstakeholders\x1a\x1cgoogle/api/annotations.proto\x1a\x15google/api/http.proto\"s\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"*\n" +
	"\x10RegisterResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"1\n" +
	"\rLoginResponse\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\"\x14\n" +
	"\x12GetAllUsersRequest\"?\n" +
	"\x13GetAllUsersResponse\x12(\n" +
	"\x05users\x18\x01 \x03(\v2\x12.stakeholders.UserR\x05users\"L\n" +
	"\x10BlockUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1c\n" +
	"\tisBlocked\x18\x02 \x01(\bR\tisBlocked\"+\n" +
	"\x11BlockUserResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"9\n" +
	"\x1bGetProfileByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\x13\n" +
	"\x11GetProfileRequest\"K\n" +
	"\x14UpdateProfileRequest\x123\n" +
	"\aprofile\x18\x01 \x01(\v2\x19.stakeholders.UserProfileR\aprofile\"/\n" +
	"\x15UpdateProfileResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xc7\x01\n" +
	"\x13UserProfileResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1c\n" +
	"\tfirstName\x18\x02 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x03 \x01(\tR\blastName\x12&\n" +
	"\x0eprofilePicture\x18\x04 \x01(\tR\x0eprofilePicture\x12\x1c\n" +
	"\tbiography\x18\x05 \x01(\tR\tbiography\x12\x14\n" +
	"\x05motto\x18\x06 \x01(\tR\x05motto\"\xa3\x01\n" +
	"\vUserProfile\x12\x1c\n" +
	"\tfirstName\x18\x01 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x02 \x01(\tR\blastName\x12&\n" +
	"\x0eprofilePicture\x18\x03 \x01(\tR\x0eprofilePicture\x12\x1c\n" +
	"\tbiography\x18\x04 \x01(\tR\tbiography\x12\x14\n" +
	"\x05motto\x18\x05 \x01(\tR\x05motto\"\xbb\x01\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1c\n" +
	"\tisBlocked\x18\x05 \x01(\bR\tisBlocked\x123\n" +
	"\aprofile\x18\x06 \x01(\v2\x19.stakeholders.UserProfileR\aprofile2\xad\x06\n" +
	"\x13StakeholdersService\x12h\n" +
	"\bRegister\x12\x1d.stakeholders.RegisterRequest\x1a\x1e.stakeholders.RegisterResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/auth/register\x12\\\n" +
	"\x05Login\x12\x1a.stakeholders.LoginRequest\x1a\x1b.stakeholders.LoginResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/auth/login\x12l\n" +
	"\vGetAllUsers\x12 .stakeholders.GetAllUsersRequest\x1a!.stakeholders.GetAllUsersResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/admin/users\x12n\n" +
	"\tBlockUser\x12\x1e.stakeholders.BlockUserRequest\x1a\x1f.stakeholders.BlockUserResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/api/admin/block-user\x12\x8a\x01\n" +
	"\x14GetProfileByUsername\x12).stakeholders.GetProfileByUsernameRequest\x1a!.stakeholders.UserProfileResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/user/profile/{username}\x12k\n" +
	"\n" +
	"GetProfile\x12\x1f.stakeholders.GetProfileRequest\x1a!.stakeholders.UserProfileResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/user/profile\x12v\n" +
	"\rUpdateProfile\x12\".stakeholders.UpdateProfileRequest\x1a#.stakeholders.UpdateProfileResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/api/user/profileB\x1fZ\x1dsoa-team-5/proto/stakeholdersb\x06proto3"

var (
	file_stakeholders_stakeholders_proto_rawDescOnce sync.Once
	file_stakeholders_stakeholders_proto_rawDescData []byte
)

func file_stakeholders_stakeholders_proto_rawDescGZIP() []byte {
	file_stakeholders_stakeholders_proto_rawDescOnce.Do(func() {
		file_stakeholders_stakeholders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stakeholders_stakeholders_proto_rawDesc), len(file_stakeholders_stakeholders_proto_rawDesc)))
	})
	return file_stakeholders_stakeholders_proto_rawDescData
}

var file_stakeholders_stakeholders_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_stakeholders_stakeholders_proto_goTypes = []any{
	(*RegisterRequest)(nil),             // 0: stakeholders.RegisterRequest
	(*RegisterResponse)(nil),            // 1: stakeholders.RegisterResponse
	(*LoginRequest)(nil),                // 2: stakeholders.LoginRequest
	(*LoginResponse)(nil),               // 3: stakeholders.LoginResponse
	(*GetAllUsersRequest)(nil),          // 4: stakeholders.GetAllUsersRequest
	(*GetAllUsersResponse)(nil),         // 5: stakeholders.GetAllUsersResponse
	(*BlockUserRequest)(nil),            // 6: stakeholders.BlockUserRequest
	(*BlockUserResponse)(nil),           // 7: stakeholders.BlockUserResponse
	(*GetProfileByUsernameRequest)(nil), // 8: stakeholders.GetProfileByUsernameRequest
	(*GetProfileRequest)(nil),           // 9: stakeholders.GetProfileRequest
	(*UpdateProfileRequest)(nil),        // 10: stakeholders.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),       // 11: stakeholders.UpdateProfileResponse
	(*UserProfileResponse)(nil),         // 12: stakeholders.UserProfileResponse
	(*UserProfile)(nil),                 // 13: stakeholders.UserProfile
	(*User)(nil),                        // 14: stakeholders.User
}
var file_stakeholders_stakeholders_proto_depIdxs = []int32{
	14, // 0: stakeholders.GetAllUsersResponse.users:type_name -> stakeholders.User
	13, // 1: stakeholders.UpdateProfileRequest.profile:type_name -> stakeholders.UserProfile
	13, // 2: stakeholders.User.profile:type_name -> stakeholders.UserProfile
	0,  // 3: stakeholders.StakeholdersService.Register:input_type -> stakeholders.RegisterRequest
	2,  // 4: stakeholders.StakeholdersService.Login:input_type -> stakeholders.LoginRequest
	4,  // 5: stakeholders.StakeholdersService.GetAllUsers:input_type -> stakeholders.GetAllUsersRequest
	6,  // 6: stakeholders.StakeholdersService.BlockUser:input_type -> stakeholders.BlockUserRequest
	8,  // 7: stakeholders.StakeholdersService.GetProfileByUsername:input_type -> stakeholders.GetProfileByUsernameRequest
	9,  // 8: stakeholders.StakeholdersService.GetProfile:input_type -> stakeholders.GetProfileRequest
	10, // 9: stakeholders.StakeholdersService.UpdateProfile:input_type -> stakeholders.UpdateProfileRequest
	1,  // 10: stakeholders.StakeholdersService.Register:output_type -> stakeholders.RegisterResponse
	3,  // 11: stakeholders.StakeholdersService.Login:output_type -> stakeholders.LoginResponse
	5,  // 12: stakeholders.StakeholdersService.GetAllUsers:output_type -> stakeholders.GetAllUsersResponse
	7,  // 13: stakeholders.StakeholdersService.BlockUser:output_type -> stakeholders.BlockUserResponse
	12, // 14: stakeholders.StakeholdersService.GetProfileByUsername:output_type -> stakeholders.UserProfileResponse
	12, // 15: stakeholders.StakeholdersService.GetProfile:output_type -> stakeholders.UserProfileResponse
	11, // 16: stakeholders.StakeholdersService.UpdateProfile:output_type -> stakeholders.UpdateProfileResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_stakeholders_stakeholders_proto_init() }
func file_stakeholders_stakeholders_proto_init() {
	if File_stakeholders_stakeholders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stakeholders_stakeholders_proto_rawDesc), len(file_stakeholders_stakeholders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stakeholders_stakeholders_proto_goTypes,
		DependencyIndexes: file_stakeholders_stakeholders_proto_depIdxs,
		MessageInfos:      file_stakeholders_stakeholders_proto_msgTypes,
	}.Build()
	File_stakeholders_stakeholders_proto = out.File
	file_stakeholders_stakeholders_proto_goTypes = nil
	file_stakeholders_stakeholders_proto_depIdxs = nil
}
