// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: tours/tours.proto

package tours

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TourDifficulty int32

const (
	TourDifficulty_EASY   TourDifficulty = 0
	TourDifficulty_MEDIUM TourDifficulty = 1
	TourDifficulty_HARD   TourDifficulty = 2
)

// Enum value maps for TourDifficulty.
var (
	TourDifficulty_name = map[int32]string{
		0: "EASY",
		1: "MEDIUM",
		2: "HARD",
	}
	TourDifficulty_value = map[string]int32{
		"EASY":   0,
		"MEDIUM": 1,
		"HARD":   2,
	}
)

func (x TourDifficulty) Enum() *TourDifficulty {
	p := new(TourDifficulty)
	*p = x
	return p
}

func (x TourDifficulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourDifficulty) Descriptor() protoreflect.EnumDescriptor {
	return file_tours_tours_proto_enumTypes[0].Descriptor()
}

func (TourDifficulty) Type() protoreflect.EnumType {
	return &file_tours_tours_proto_enumTypes[0]
}

func (x TourDifficulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourDifficulty.Descriptor instead.
func (TourDifficulty) EnumDescriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{0}
}

type TourStatus int32

const (
	TourStatus_DRAFT     TourStatus = 0
	TourStatus_PUBLISHED TourStatus = 1
	TourStatus_ARCHIVED  TourStatus = 2
)

// Enum value maps for TourStatus.
var (
	TourStatus_name = map[int32]string{
		0: "DRAFT",
		1: "PUBLISHED",
		2: "ARCHIVED",
	}
	TourStatus_value = map[string]int32{
		"DRAFT":     0,
		"PUBLISHED": 1,
		"ARCHIVED":  2,
	}
)

func (x TourStatus) Enum() *TourStatus {
	p := new(TourStatus)
	*p = x
	return p
}

func (x TourStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tours_tours_proto_enumTypes[1].Descriptor()
}

func (TourStatus) Type() protoreflect.EnumType {
	return &file_tours_tours_proto_enumTypes[1]
}

func (x TourStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourStatus.Descriptor instead.
func (TourStatus) EnumDescriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{1}
}

type CreateTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Price         float32                `protobuf:"fixed32,7,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTourRequest) Reset() {
	*x = CreateTourRequest{}
	mi := &file_tours_tours_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourRequest) ProtoMessage() {}

func (x *CreateTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourRequest.ProtoReflect.Descriptor instead.
func (*CreateTourRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTourRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTourRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTourRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTourRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *CreateTourRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateTourRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateTourRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetAllToursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllToursRequest) Reset() {
	*x = GetAllToursRequest{}
	mi := &file_tours_tours_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllToursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllToursRequest) ProtoMessage() {}

func (x *GetAllToursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllToursRequest.ProtoReflect.Descriptor instead.
func (*GetAllToursRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{1}
}

type GetAllToursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*Tour                `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllToursResponse) Reset() {
	*x = GetAllToursResponse{}
	mi := &file_tours_tours_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllToursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllToursResponse) ProtoMessage() {}

func (x *GetAllToursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllToursResponse.ProtoReflect.Descriptor instead.
func (*GetAllToursResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllToursResponse) GetTours() []*Tour {
	if x != nil {
		return x.Tours
	}
	return nil
}

type CreateKeyPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	ImagePath     string                 `protobuf:"bytes,5,opt,name=imagePath,proto3" json:"imagePath,omitempty"`
	TourId        string                 `protobuf:"bytes,6,opt,name=tourId,proto3" json:"tourId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeyPointRequest) Reset() {
	*x = CreateKeyPointRequest{}
	mi := &file_tours_tours_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyPointRequest) ProtoMessage() {}

func (x *CreateKeyPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyPointRequest.ProtoReflect.Descriptor instead.
func (*CreateKeyPointRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{3}
}

func (x *CreateKeyPointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateKeyPointRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateKeyPointRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateKeyPointRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CreateKeyPointRequest) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *CreateKeyPointRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type AddReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	Rating        int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReviewRequest) Reset() {
	*x = AddReviewRequest{}
	mi := &file_tours_tours_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReviewRequest) ProtoMessage() {}

func (x *AddReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReviewRequest.ProtoReflect.Descriptor instead.
func (*AddReviewRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{4}
}

func (x *AddReviewRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *AddReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *AddReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type AddReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReviewResponse) Reset() {
	*x = AddReviewResponse{}
	mi := &file_tours_tours_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReviewResponse) ProtoMessage() {}

func (x *AddReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReviewResponse.ProtoReflect.Descriptor instead.
func (*AddReviewResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{5}
}

func (x *AddReviewResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DrawOnMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrawOnMapRequest) Reset() {
	*x = DrawOnMapRequest{}
	mi := &file_tours_tours_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrawOnMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawOnMapRequest) ProtoMessage() {}

func (x *DrawOnMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawOnMapRequest.ProtoReflect.Descriptor instead.
func (*DrawOnMapRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{6}
}

func (x *DrawOnMapRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type DrawOnMapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourData      string                 `protobuf:"bytes,1,opt,name=tourData,proto3" json:"tourData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrawOnMapResponse) Reset() {
	*x = DrawOnMapResponse{}
	mi := &file_tours_tours_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrawOnMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawOnMapResponse) ProtoMessage() {}

func (x *DrawOnMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawOnMapResponse.ProtoReflect.Descriptor instead.
func (*DrawOnMapResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{7}
}

func (x *DrawOnMapResponse) GetTourData() string {
	if x != nil {
		return x.TourData
	}
	return ""
}

type SimulatePositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulatePositionRequest) Reset() {
	*x = SimulatePositionRequest{}
	mi := &file_tours_tours_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulatePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulatePositionRequest) ProtoMessage() {}

func (x *SimulatePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulatePositionRequest.ProtoReflect.Descriptor instead.
func (*SimulatePositionRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{8}
}

func (x *SimulatePositionRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SimulatePositionRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type SimulatePositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulatePositionResponse) Reset() {
	*x = SimulatePositionResponse{}
	mi := &file_tours_tours_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulatePositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulatePositionResponse) ProtoMessage() {}

func (x *SimulatePositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulatePositionResponse.ProtoReflect.Descriptor instead.
func (*SimulatePositionResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{9}
}

func (x *SimulatePositionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Tour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    TourDifficulty         `protobuf:"varint,5,opt,name=difficulty,proto3,enum=tours.TourDifficulty" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        TourStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=tours.TourStatus" json:"status,omitempty"`
	Price         float32                `protobuf:"fixed32,8,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tour) Reset() {
	*x = Tour{}
	mi := &file_tours_tours_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tour) ProtoMessage() {}

func (x *Tour) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tour.ProtoReflect.Descriptor instead.
func (*Tour) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{10}
}

func (x *Tour) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tour) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Tour) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tour) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tour) GetDifficulty() TourDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return TourDifficulty_EASY
}

func (x *Tour) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Tour) GetStatus() TourStatus {
	if x != nil {
		return x.Status
	}
	return TourStatus_DRAFT
}

func (x *Tour) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type KeyPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	ImagePath     string                 `protobuf:"bytes,6,opt,name=imagePath,proto3" json:"imagePath,omitempty"`
	TourId        string                 `protobuf:"bytes,7,opt,name=tourId,proto3" json:"tourId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyPoint) Reset() {
	*x = KeyPoint{}
	mi := &file_tours_tours_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPoint) ProtoMessage() {}

func (x *KeyPoint) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPoint.ProtoReflect.Descriptor instead.
func (*KeyPoint) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{11}
}

func (x *KeyPoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KeyPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyPoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KeyPoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *KeyPoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *KeyPoint) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *KeyPoint) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

var File_tours_tours_proto protoreflect.FileDescriptor

const file_tours_tours_proto_rawDesc = "" +
	"\n" +
	"\x11tours/tours.proto\x12\x05tours\x1a\x1cgoogle/api/annotations.proto\x1a\x15google/api/http.proto\"\xc3\x01\n" +
	"\x11CreateTourRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\a \x01(\x02R\x05price\"\x14\n" +
	"\x12GetAllToursRequest\"8\n" +
	"\x13GetAllToursResponse\x12!\n" +
	"\x05tours\x18\x01 \x03(\v2\v.tours.TourR\x05tours\"\xbd\x01\n" +
	"\x15CreateKeyPointRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x1c\n" +
	"\timagePath\x18\x05 \x01(\tR\timagePath\x12\x16\n" +
	"\x06tourId\x18\x06 \x01(\tR\x06tourId\"\\\n" +
	"\x10AddReviewRequest\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\tR\x06tourId\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"+\n" +
	"\x11AddReviewResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"*\n" +
	"\x10DrawOnMapRequest\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\tR\x06tourId\"/\n" +
	"\x11DrawOnMapResponse\x12\x1a\n" +
	"\btourData\x18\x01 \x01(\tR\btourData\"S\n" +
	"\x17SimulatePositionRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"2\n" +
	"\x18SimulatePositionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xf0\x01\n" +
	"\x04Tour\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x125\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\x0e2\x15.tours.TourDifficultyR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12)\n" +
	"\x06status\x18\a \x01(\x0e2\x11.tours.TourStatusR\x06status\x12\x14\n" +
	"\x05price\x18\b \x01(\x02R\x05price\"\xc0\x01\n" +
	"\bKeyPoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x1c\n" +
	"\timagePath\x18\x06 \x01(\tR\timagePath\x12\x16\n" +
	"\x06tourId\x18\a \x01(\tR\x06tourId*0\n" +
	"\x0eTourDifficulty\x12\b\n" +
	"\x04EASY\x10\x00\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x01\x12\b\n" +
	"\x04HARD\x10\x02*4\n" +
	"\n" +
	"TourStatus\x12\t\n" +
	"\x05DRAFT\x10\x00\x12\r\n" +
	"\tPUBLISHED\x10\x01\x12\f\n" +
	"\bARCHIVED\x10\x022\xcf\x04\n" +
	"\fToursService\x12J\n" +
	"\n" +
	"CreateTour\x12\x18.tours.CreateTourRequest\x1a\v.tours.Tour\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/api/tours\x12X\n" +
	"\vGetAllTours\x12\x19.tours.GetAllToursRequest\x1a\x1a.tours.GetAllToursResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/api/tours\x12Z\n" +
	"\x0eCreateKeyPoint\x12\x1c.tours.CreateKeyPointRequest\x1a\x0f.tours.KeyPoint\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/keypoints\x12e\n" +
	"\tAddReview\x12\x17.tours.AddReviewRequest\x1a\x18.tours.AddReviewResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/tours/{tourId}/review\x12_\n" +
	"\tDrawOnMap\x12\x17.tours.DrawOnMapRequest\x1a\x18.tours.DrawOnMapResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/tours/{tourId}/map\x12u\n" +
	"\x10SimulatePosition\x12\x1e.tours.SimulatePositionRequest\x1a\x1f.tours.SimulatePositionResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/tourist/positionB$Z\"soa-team-5/api-gateway/proto/toursb\x06proto3"

var (
	file_tours_tours_proto_rawDescOnce sync.Once
	file_tours_tours_proto_rawDescData []byte
)

func file_tours_tours_proto_rawDescGZIP() []byte {
	file_tours_tours_proto_rawDescOnce.Do(func() {
		file_tours_tours_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tours_tours_proto_rawDesc), len(file_tours_tours_proto_rawDesc)))
	})
	return file_tours_tours_proto_rawDescData
}

var file_tours_tours_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tours_tours_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_tours_tours_proto_goTypes = []any{
	(TourDifficulty)(0),              // 0: tours.TourDifficulty
	(TourStatus)(0),                  // 1: tours.TourStatus
	(*CreateTourRequest)(nil),        // 2: tours.CreateTourRequest
	(*GetAllToursRequest)(nil),       // 3: tours.GetAllToursRequest
	(*GetAllToursResponse)(nil),      // 4: tours.GetAllToursResponse
	(*CreateKeyPointRequest)(nil),    // 5: tours.CreateKeyPointRequest
	(*AddReviewRequest)(nil),         // 6: tours.AddReviewRequest
	(*AddReviewResponse)(nil),        // 7: tours.AddReviewResponse
	(*DrawOnMapRequest)(nil),         // 8: tours.DrawOnMapRequest
	(*DrawOnMapResponse)(nil),        // 9: tours.DrawOnMapResponse
	(*SimulatePositionRequest)(nil),  // 10: tours.SimulatePositionRequest
	(*SimulatePositionResponse)(nil), // 11: tours.SimulatePositionResponse
	(*Tour)(nil),                     // 12: tours.Tour
	(*KeyPoint)(nil),                 // 13: tours.KeyPoint
}
var file_tours_tours_proto_depIdxs = []int32{
	12, // 0: tours.GetAllToursResponse.tours:type_name -> tours.Tour
	0,  // 1: tours.Tour.difficulty:type_name -> tours.TourDifficulty
	1,  // 2: tours.Tour.status:type_name -> tours.TourStatus
	2,  // 3: tours.ToursService.CreateTour:input_type -> tours.CreateTourRequest
	3,  // 4: tours.ToursService.GetAllTours:input_type -> tours.GetAllToursRequest
	5,  // 5: tours.ToursService.CreateKeyPoint:input_type -> tours.CreateKeyPointRequest
	6,  // 6: tours.ToursService.AddReview:input_type -> tours.AddReviewRequest
	8,  // 7: tours.ToursService.DrawOnMap:input_type -> tours.DrawOnMapRequest
	10, // 8: tours.ToursService.SimulatePosition:input_type -> tours.SimulatePositionRequest
	12, // 9: tours.ToursService.CreateTour:output_type -> tours.Tour
	4,  // 10: tours.ToursService.GetAllTours:output_type -> tours.GetAllToursResponse
	13, // 11: tours.ToursService.CreateKeyPoint:output_type -> tours.KeyPoint
	7,  // 12: tours.ToursService.AddReview:output_type -> tours.AddReviewResponse
	9,  // 13: tours.ToursService.DrawOnMap:output_type -> tours.DrawOnMapResponse
	11, // 14: tours.ToursService.SimulatePosition:output_type -> tours.SimulatePositionResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_tours_tours_proto_init() }
func file_tours_tours_proto_init() {
	if File_tours_tours_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tours_tours_proto_rawDesc), len(file_tours_tours_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tours_tours_proto_goTypes,
		DependencyIndexes: file_tours_tours_proto_depIdxs,
		EnumInfos:         file_tours_tours_proto_enumTypes,
		MessageInfos:      file_tours_tours_proto_msgTypes,
	}.Build()
	File_tours_tours_proto = out.File
	file_tours_tours_proto_goTypes = nil
	file_tours_tours_proto_depIdxs = nil
}
